################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_UPPER_SRCS := 
ASM_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CXX_UPPER_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
X_SRCS := 
SRC_SRCS := 
C_SRCS := 
CC_UPPER_DEPS := 
C++_UPPER_DEPS := 
CXX_UPPER_DEPS := 
CPP_UPPER_DEPS := 
C_UPPER_DEPS := 
SRC_UPPER_DEPS := 
S_DEPS := 
C_DEPS := 
SRC_DEPS := 
LINKER_OUTPUT_OUTPUTS := 
CC_DEPS := 
C++_DEPS := 
CXX_DEPS := 
OBJS := 
ASM_DEPS := 
LIBRARY_GENERATOR_OUTPUTTYPE_OUTPUTS := 
S_UPPER_DEPS := 
OBJCOPY_OUTPUTTYPE_OUTPUTS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/sample/sample_vdc5 \
src/sample/graphics \
src/sample/graphics/video_decoder \
src/sample/graphics/rendering \
src/sample/graphics/common \
src/sample/graphics/common/lcd_panel \
src \
src/drivers/vdec/src \
src/drivers/vdc5/src \
src/drivers/ssif/src \
src/drivers/sdhi/userdef \
src/drivers/sdhi/src/sd/sdio \
src/drivers/sdhi/src/sd/access \
src/drivers/scux/scux_driver \
src/drivers/scif_uart/userdef \
src/drivers/scif_uart/scif_uart_driver \
src/drivers/rtc \
src/drivers/rspi/userdef \
src/drivers/rspi/rspi_driver \
src/drivers/riic/userdef \
src/drivers/riic/riic_driver \
src/drivers/ostm \
src/drivers/keyscanuart \
src/drivers/intc/userdef \
src/drivers/intc/intc_driver \
src/drivers/common/userdef \
src/drivers/common/common_driver \
src/drivers/adc \
src/common \
src/board_settings \
src/RGPNCG/src \
src/RETWgraphics \
src/RETWapp/Audio \
src/RETWapp/Audio/parser \
src/RETWapp/Audio/parser/MP3/src \
src/RETWapp/Audio/parser/ID3/src \
src/RETWapp/Audio/command_scux \
src/RETWapp/Audio/command_dec \
src/RETWapp/Audio/command_dec/asm \
src/RETWapp/Audio/command \
src/RETWapp/Audio/audio \
src/RETWOpenVG/text \
src/RETWOpenVG \
src/RETWHUD \
src/RETWFreeType \
compiler_specific/src \
compiler_specific/asm \

